## CORS Configurations
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:8080,http://localhost:8081
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
issuer=http://localhost:8080
