## CORS Configurations
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://auth-service:8080,http://employee-service:8081
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
issuer=http://auth-service:8080
