spring.profiles.active=local
server.port=8082
spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=true

## Logging Configurations
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty=DEBUG

## Gateway Routes
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://employee-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/employee, /api/v1/employee/**,/api/v1/department, /api/v1/department/**

spring.cloud.gateway.routes[1].id=authentication-server
spring.cloud.gateway.routes[1].uri=lb://authentication-server
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/auth/**

## CORS Configurations
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://auth-service:8080,http://employee-service:8081
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

## Security Configurations
#issuer=http://localhost:8080






