server.port=9000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.config.server.git.uri=https://github.com/vhee4/cloud-config.git
spring.cloud.config.server.git.clone-on-start=true


spring.application.name=ConfigServer
#spring.cloud.config.server.bootstrap=true


# Use composite config (Git + Native)
#spring.cloud.config.server.composite[0].type=git
#spring.cloud.config.server.composite[0].uri=https://github.com/vhee4/cloud-config.git
#spring.cloud.config.server.composite[0].clone-on-start=true
#spring.cloud.config.server.composite[1].type=native
#spring.cloud.config.server.composite[1].search-locations=classpath:/config
