spring.application.name=authentication-server
spring.cloud.config.uri=http://config-server:9000
spring.cloud.config.enabled=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
spring.cloud.config.label=main
spring.config.import=configserver:

