spring.application.name=authentication-server
spring.cloud.config.enabled=true
spring.cloud.config.uri=http://localhost:9000
spring.cloud.config.label=main
spring.config.import=configserver:
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

